In [1]:
import cv2
import matplotlib.pyplot as plt
import os
import glob
import numpy as np

In [2]:
X_dn = np.load('C:/Users/PDL LAB17/Desktop/IPML_raj_katkar/X_dn_third_train.npy')

In [3]:
print(X_dn.shape)

(22860, 18151)


In [4]:
import cupy as cp

C:\Users\PDL LAB17\anaconda3\envs\raj_k\lib\site-packages\cupy\_environment.py:206: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  'CUDA path could not be detected.'


In [5]:
X_gpu = cp.asarray(X_dn)

In [6]:
print(X_gpu.shape)

(22860, 18151)


In [7]:
result_gpu = cp.dot(X_gpu, X_gpu.T)

In [8]:
result = cp.asnumpy(result_gpu)

In [9]:
result1 = result/18151

In [17]:
result2  = result1.astype(np.float16)

In [19]:
print(result2)

[[0.014046 0.00755  0.011406 ... 0.01212  0.00584  0.002258]
 [0.00755  0.003305 0.00496  ... 0.00303  0.002644 0.00628 ]
 [0.011406 0.00496  0.004463 ... 0.01399  0.011955 0.01212 ]
 ...
 [0.01212  0.00303  0.01399  ... 0.01151  0.001708 0.00958 ]
 [0.00584  0.002644 0.011955 ... 0.001708 0.01228  0.003967]
 [0.002258 0.00628  0.01212  ... 0.00958  0.003967 0.003635]]


In [18]:
np.save('C_dd_1.npy',result2)

In [ ]:
for i in range(22860):
    for j in range(18151):
        result[i][j] = result[i][j]/18151

In [11]:
np.save('Covariance_180_127_train.npy',result1)

In [12]:
print(result)

[[255 137 207 ... 220 106  41]
 [137  60  90 ...  55  48 114]
 [207  90  81 ... 254 217 220]
 ...
 [220  55 254 ... 209  31 174]
 [106  48 217 ...  31 223  72]
 [ 41 114 220 ... 174  72  66]]


In [13]:
np.save('Covariance_180_127_train_without_div.npy',result)

In [10]:
print(result1)

[[0.01404881 0.00754779 0.01140433 ... 0.01212054 0.0058399  0.00225883]
 [0.00754779 0.0033056  0.0049584  ... 0.00303014 0.00264448 0.00628065]
 [0.01140433 0.0049584  0.00446256 ... 0.01399372 0.01195526 0.01212054]
 ...
 [0.01212054 0.00303014 0.01399372 ... 0.01151452 0.00170789 0.00958625]
 [0.0058399  0.00264448 0.01195526 ... 0.00170789 0.01228582 0.00396672]
 [0.00225883 0.00628065 0.01212054 ... 0.00958625 0.00396672 0.00363616]]
