In [3]:
import numpy as np

In [4]:
C:/Users/rajhk/Desktop/IIT/ipml projject

SyntaxError: invalid syntax (3612754219.py, line 1)

In [5]:
eigen_values = np.load('C:/Users/rajhk/Desktop/IIT/ipml projject/eig_values_1.npy')

In [6]:
eigen_vectors = np.load('C:/Users/rajhk/Desktop/IIT/ipml projject/eig_vectors_1.npy')

In [7]:
print(eigen_vectors.shape)
print(eigen_values.shape)

(22860, 22860)
(22860,)


In [8]:
print(eigen_values)

[ -1.2311611  -1.2277523  -1.2260431 ...   1.2283589   1.229796
 160.58165  ]


In [9]:
print(eigen_vectors)

[[-8.0555044e-03  9.1236467e-03 -3.9888136e-03 ... -5.2905730e-03
   1.4294059e-02  6.6192057e-03]
 [-9.6453540e-04  2.8413800e-03  7.4169966e-03 ... -5.1074689e-03
   1.3262313e-03  6.6135526e-03]
 [-9.4314190e-03 -6.2000733e-03  1.8839445e-03 ... -2.5880570e-03
  -2.3294184e-03  6.6084266e-03]
 ...
 [ 1.5669797e-03 -3.5238930e-03  9.7422972e-03 ...  8.6778804e-05
  -7.5723305e-03  6.5973802e-03]
 [ 5.3078090e-03  1.0352592e-02  5.6625297e-04 ... -3.4211599e-03
   8.6505460e-03  6.6133547e-03]
 [ 3.7231985e-05 -1.9158061e-03 -9.3621938e-03 ...  4.4245494e-04
   1.8528271e-02  6.5937573e-03]]


In [10]:
sorted_indices = np.argsort(eigen_values)[::-1]
sorted_eigenvalues = eigen_values[sorted_indices]
sorted_eigenvectors = eigen_vectors[:, sorted_indices]

In [11]:
PC = sorted_eigenvectors[:200,:]

In [12]:
PC.shape

(200, 22860)

In [13]:
X_data = np.load('C:/Users/rajhk/Desktop/IIT/ipml projject/X_data_third.npy')

Y_data = np.load('C:/Users/rajhk/Desktop/IIT/ipml projject/Y_data_third.npy')


In [14]:
from sklearn.model_selection import train_test_split
 
X_train, X_test, y_train, y_test = train_test_split(X_data, Y_data, test_size = 0.2, random_state = 42)

In [15]:
print(X_train.shape)
print(X_test.shape)

(18151, 22860)
(4538, 22860)


In [16]:
X_bar_pn_train = np.dot(PC,X_train.T)
X_bar_pn_test = np.dot(PC,X_test.T)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
Knn = KNeighborsClassifier(n_neighbors=51)
Knn.fit(X_bar_pn_train.T, y_train)

KNeighborsClassifier(n_neighbors=51)

In [21]:
y_pred = Knn.predict(X_bar_pn_test.T)

In [22]:
from sklearn.metrics import confusion_matrix
 
cm = confusion_matrix(y_test, y_pred)

In [23]:
print(cm)

[[447   2  10   0   0   8   0   4   0   0]
 [  0  62   1 126 130   0   0 100   0  81]
 [  0   1 466   1   0   0   5   0   0   0]
 [  0 126   0  48 123   0   0 105   0  67]
 [  1 128   1 106  41   0   0  87   0  76]
 [  5   1   4   0   0 447   4   0   0   0]
 [  1   0  17   1   1   7 436   1   1   0]
 [  0 120   1 107 124   0   0  28   0  70]
 [ 13   1  48   0   2   7  16   0 295   0]
 [  0 132   0  90 105   0   0  83   0  17]]


In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.503966505068312